export const DEMO_MEDIA = [
  {
    id: "sample-image-authentic",
    title: "Sample Image 01",
    type: "image",
    filename: "test2.jpeg",
    assetUrl: "/demo/test2.jpeg",
    mimeType: "image/jpeg",
    description: "Sample image for a fast authenticity check inside the product workflow.",
    preferredProvider: "gemini",
    featureHighlight: "Authentic sample",
  },
  {
    id: "sample-image-deepfake",
    title: "Sample Image 02",
    type: "image",
    filename: "test4.jpg",
    assetUrl: "/demo/test4.jpg",
    mimeType: "image/jpeg",
    description: "Sample image intended to produce a positive deepfake-style result in the product flow.",
    preferredProvider: "local",
    featureHighlight: "Use only Our own model",
    providerWarning: "Gemini fails on this sample. Use only Our own model.",
  },
  {
    id: "timeline-demo-1",
    title: "Timeline Demo 01",
    type: "video",
    filename: "timeline-demo-1.mp4",
    assetUrl: "/demo/timeline-demo-1.mp4",
    mimeType: "video/mp4",
    description: "Add a validated 11-second clip here to demonstrate exact manipulated segment localization.",
    preferredProvider: "local",
    enableMultiface: false,
    featureHighlight: "Segment localization",
    validated: true,
  },
  {
    id: "timeline-demo-2",
    title: "Timeline Demo 02",
    type: "video",
    filename: "timeline-demo-2.mp4",
    assetUrl: "/demo/timeline-demo-2.mp4",
    mimeType: "video/mp4",
    description: "Add a second validated 11-second clip here to compare overall verdict versus exact suspicious windows.",
    preferredProvider: "local",
    enableMultiface: false,
    featureHighlight: "Selling-point clip",
    validated: true,
  },
];
